# Generated by Django 2.2.24 on 2022-01-02 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0124_update_default_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(help_text='A short, unique code for the problem, used in the url after /problem/', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Problem code must be ^[a-z0-9_]+$')], verbose_name='problem code'),
        ),
    ]
