# Generated by Django 2.2.24 on 2022-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0125_allow_underscore_in_prob_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_only',
            field=models.BooleanField(default=False, help_text='If this language is only allowed submitted using file or not', verbose_name='File-only language'),
        ),
    ]
