# Generated by Django 2.2.24 on 2022-01-31 03:20

import django.db.models.deletion
from django.db import migrations, models

import judge.models.runtime


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0125_allow_underscore_in_prob_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_only',
            field=models.BooleanField(default=False, help_text='If this language is only allowed submitted using file or not', verbose_name='File-only language'),
        ),
        migrations.AddField(
            model_name='language',
            name='file_size_limit',
            field=models.IntegerField(blank=True, default=0, help_text='Limit of file size (in MB) if allow submit via file', verbose_name='Limit of file size'),
        ),
        migrations.AddField(
            model_name='language',
            name='include_in_problem',
            field=models.BooleanField(default=False, help_text='If true, this language will be added to all problems', verbose_name='Include in problems'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(default=judge.models.runtime.Language.get_default_language_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='judge.Language', verbose_name='preferred language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='key',
            field=models.CharField(help_text='The identifier for this language; the same as its executor id for judges.', max_length=10, unique=True, verbose_name='short identifier'),
        ),
    ]
