# Generated by Django 2.2.24 on 2022-02-06 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0126_language_file_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.FloatField(help_text="Points awarded for problem completion. Points are displayed with a 'p' suffix if partial. <strong>1-1.5:</strong> beginner problems; <strong>1.5-2:</strong> simple algorithm (binary search, sieve, etc.); <strong>2-3:</strong> advanced algorithm (dp, dijkstra, dsu, etc.); <strong>2.5-3.5: 1st probs of VOI; <strong>3.5-4.5:</strong> 2nd probs of VOI; <strong>4.5-6:</strong> 3rd probs of VOI.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='points'),
        ),
    ]
