# Generated by Django 2.2.24 on 2022-01-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0126_language_file_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='key',
            field=models.CharField(help_text='The identifier for this language; the same as its executor id for judges.', max_length=10, unique=True, verbose_name='short identifier'),
        ),
    ]
