# Generated by Django 2.2.24 on 2022-01-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0127_increase_key_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_size_limit',
            field=models.IntegerField(blank=True, default=0, help_text='Limit of file size (in MB) if allow submit via file', verbose_name='Limit of file size'),
        ),
    ]
