# Generated by Django 2.2.24 on 2022-04-01 16:52

from django.db import migrations, models

import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0128_problem_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='problem body'),
        ),
    ]
