# Generated by Django 2.2.24 on 2022-04-11 16:31

from django.db import migrations, models

import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0137_output_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemclarification',
            name='description',
            field=models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='clarification body'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='description',
            field=models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='translated description'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='editorial content'),
        ),
    ]
