# Generated by Django 2.2.24 on 2022-04-13 08:47

from django.db import migrations, models

import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0138_auto_20220411_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=models.TextField(blank=True, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='editorial content'),
        ),
    ]
