# Generated by Django 2.2.24 on 2022-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0144_organization_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_unlisted',
            field=models.BooleanField(default=True, help_text='Organization will not be listed', verbose_name='is unlisted organization?'),
        ),
    ]
