# Generated by Django 2.2.24 on 2022-04-19 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0145_organization_is_unlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=settings.CLAOJ_DISPLAY_RANKS, default='user', max_length=10, verbose_name='display rank'),
        ),
    ]
