# Generated by Django 2.2.24 on 2022-04-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_blog_post_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='performance_points',
            field=models.FloatField(default=0),
        ),
    ]
