# Generated by Django 2.2.24 on 2022-04-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0149_update_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='include_in_problem',
            field=models.BooleanField(default=False, help_text='If true, this language will be added to all problems', verbose_name='Include in problems'),
        ),
    ]
