# Generated by Django 2.2.24 on 2022-06-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_blog_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='push_announcements',
            field=models.BooleanField(default=False, help_text='Notify users when there are new announcements.', verbose_name='push announcements'),
        ),
        migrations.CreateModel(
            name='ContestAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='announcement title')),
                ('description', models.TextField(verbose_name='announcement body')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='announcement timestamp')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Contest', verbose_name='announced contest')),
            ],
        ),
    ]
