# Generated by Django 2.2.24 on 2022-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_username_display_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='virtual_count',
            field=models.IntegerField(default=0, verbose_name='the amount of virtual participants'),
        ),
    ]
